### ISSUE TITLE
Add scientific notation of a number

### ISSUE THREAD

**Issue by hubciorz** [howsecureismypassword/modules-purescript#9]
The primary issue with displaying a name of a number is that it is not clear if it's the short scale or the long scale. For example, 8 nonillion years may mean 8 * 10^30 (e.g. in US) or 8 * 10^54 (e.g. in most countries in Europe)

![image](https://user-images.githubusercontent.com/6502822/89624169-25420880-d896-11ea-8a26-6be31fcb44a2.png)

The solution is to add the scientific notation representation of the number of years.
Reference: https://en.wikipedia.org/wiki/Long_and_short_scales

**Comment by hubciorz** [comment]
Sorry, I just noticed I posted it in on wrong repo.

**Comment by smallhadroncollider** [comment]
Thanks for this. The website repo is private, so this is as good a place as any.

I think to the average person using the site the difference between short-scale and long-scale numbers probably isn't going to mean much.

However, there are two solutions in the works:

1. A way to show how long it will take in full (e.g. 8,000,000,000,000,000,000,000...) – some of the appeal of the site is getting the numbers big, so I think this is going to be more entertaining for the average user.
2. Translations: the number names are part of the translation, so can be tweaked for those languages where it is appropriate
